services:
  products-db:
    image: postgres:17-alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: product
      POSTGRES_PASSWORD: product123
    volumes:
      - products-data:/var/lib/postgresql/data

  orders-db:
    image: postgres:17-alpine
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: order
      POSTGRES_PASSWORD: order123
    volumes:
      - orders-data:/var/lib/postgresql/data

  customers-db:
    image: postgres:17-alpine
    ports:
      - "5437:5432"
    environment:
      POSTGRES_DB: customers
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: customer123
    volumes:
      - customers-data:/var/lib/postgresql/data

  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"

  product-service:
    build: ./product-service
    ports:
      - "8081:8081"
    depends_on:
      - products-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://products-db:5432/products
      SPRING_DATASOURCE_USERNAME: product
      SPRING_DATASOURCE_PASSWORD: product123
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    depends_on:
      - orders-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://orders-db:5432/orders
      SPRING_DATASOURCE_USERNAME: order
      SPRING_DATASOURCE_PASSWORD: order123
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/

  customer-service:
    build: ./customer-service
    ports:
      - "8083:8083"
    depends_on:
      - customers-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://customers-db:5432/customers
      SPRING_DATASOURCE_USERNAME: customer
      SPRING_DATASOURCE_PASSWORD: customer123
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/

  keycloak:
    image: docker.io/keycloak/keycloak:25.0.0
    command: start-dev --import-realm --health-enabled=true
    ports:
      - "9001:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json

  gateway-service:
    build: ./gateway-service
    ports:
      - "9000:8080"
    depends_on:
      - discovery-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/

volumes:
  products-data:
  orders-data:
  customers-data:
