services:
  products-db:
    image: postgres:17-alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: product
      POSTGRES_PASSWORD: product123
    volumes:
      - products-data:/var/lib/postgresql/data

  orders-db:
    image: postgres:17-alpine
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: order
      POSTGRES_PASSWORD: order123
    volumes:
      - orders-data:/var/lib/postgresql/data

  customers-db:
    image: postgres:17-alpine
    ports:
      - "5437:5432"
    environment:
      POSTGRES_DB: customers
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: customer123
    volumes:
      - customers-data:/var/lib/postgresql/data

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      - products-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://products-db:5432/products
      SPRING_DATASOURCE_USERNAME: product
      SPRING_DATASOURCE_PASSWORD: product123

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      - orders-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://orders-db:5432/orders
      SPRING_DATASOURCE_USERNAME: order
      SPRING_DATASOURCE_PASSWORD: order123

  customer-service:
    build: ./customer-service
    container_name: customer-service
    ports:
      - "8083:8083"
    depends_on:
      - customers-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://customers-db:5432/customers
      SPRING_DATASOURCE_USERNAME: customer
      SPRING_DATASOURCE_PASSWORD: customer123

  keycloak:
    image: docker.io/keycloak/keycloak:25.0.0
    container_name: keycloak
    command: start-dev --import-realm --health-enabled=true
    ports:
      - "9001:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "9000:9000"
    depends_on:
      - keycloak
      - product-service
      - order-service
      - customer-service
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/textileco
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/textileco/protocol/openid-connect/certs
      PRODUCT_SERVICE_URI: http://product-service:8081
      ORDER_SERVICE_URI: http://order-service:8082
      CUSTOMER_SERVICE_URI: http://customer-service:8083

volumes:
  products-data:
  orders-data:
  customers-data:
