
server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5436/orders
    username: order
    password: order123
  jpa:
    hibernate:
      ddl-auto: update
